### ISSUE TITLE
linea del tiempo de las web

### ISSUE THREAD

**Issue by gilbertovelasco1** [SistemasTecTlaxiaco/actividad-7-gilbertovelasco1#1]
[Línea De Tiempo web 1 2 y3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-gilbertovelasco1/files/9805793/Linea.De.Tiempo.web.1.2.y3.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
